### ISSUE TITLE
Updated maps for 2023/24?

### ISSUE THREAD

**Issue by JPhusion** [ChrisMusson/FPL-ID-Map#1]
Hey Chris, 

Are you working on a new map for the upcoming season?

Thanks.

(It josh btw you might remember me from the last 2 years when i asked)

**Comment by ChrisMusson** [comment]
Hey Josh,

I will be updating it for the upcoming season, but probably not for a couple of weeks

**Comment by JPhusion** [comment]
Alright thank you very much!

**Comment by JPhusion** [comment]
Hey Chris, any updates?

**Comment by ChrisMusson** [comment]
Hey, afraid not for a while still. Suffered some water damage to my laptop so have lost all of my scripts, which will take time to rewrite.

Sorry about that

**Comment by ChrisMusson** [comment]
Hello again. I'm sorry it took so long, but everything is updated now. I have also included the main scripts in case you want to update things yourself rather than wait for me in the future. The workflow is
1. Run `python add_new_players.py` - this will update the FPL 23-24 CSV and also add any players that aren't currently in `Master.csv` to the bottom of the FBRef, TransferMarkt, and Understat CSVs.
2. Find the IDs of these newly added players and update the FBRef, TransferMarkt, and Understat CSVs.
3. Run `python generate_master.py`. This will rebuild the master CSV from scratch, including the new players that were just found.
